"""Z1.4 — migratsiya testlari.

Acceptance criteria: `upgrade head` -> `downgrade base` -> `upgrade head` xatosiz,
va modellar migratsiya bilan mos (drift yo'q).
"""

from __future__ import annotations

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

CORE_DIR = Path(__file__).resolve().parents[1]


@pytest.fixture
def alembic_config(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Config:
    db_path = tmp_path / "migration_test.db"
    monkeypatch.setenv("ZET_DATABASE_URL", f"sqlite+aiosqlite:///{db_path}")

    from zet.config import get_settings

    get_settings.cache_clear()

    cfg = Config(str(CORE_DIR / "alembic.ini"))
    cfg.set_main_option("script_location", str(CORE_DIR / "alembic"))
    return cfg


def test_upgrade_downgrade_upgrade(alembic_config: Config) -> None:
    """Migratsiya ikki tomonlama ishlashi shart."""
    command.upgrade(alembic_config, "head")
    command.downgrade(alembic_config, "base")
    command.upgrade(alembic_config, "head")


def test_no_schema_drift(alembic_config: Config) -> None:
    """Modellar va migratsiya bir-biriga mos bo'lishi kerak.

    Model o'zgartirilib, migratsiya yozilmasa — bu test qizaradi.
    """
    command.upgrade(alembic_config, "head")
    try:
        command.check(alembic_config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - faqat drift bo'lsa
        pytest.fail(f"Migratsiya modellardan orqada qolgan: {exc}")


def test_single_head(alembic_config: Config) -> None:
    """Bitta chiziqli tarix — parallel head'lar bo'lmasligi kerak."""
    from alembic.script import ScriptDirectory

    script = ScriptDirectory.from_config(alembic_config)
    assert len(script.get_heads()) == 1
