"""core schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-11 16:22:58.486285
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import zet.db.base
from zet.db.base import JSONType, UTCDateTime, enum_column  # noqa: F401

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('ts', zet.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=True),
    sa.Column('permission_level', sa.Enum('read', 'write', 'execute', 'admin', name='permissionlevel_enum', native_enum=False, length=32), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)
        batch_op.create_index('ix_audit_log_ts_action', ['ts', 'action'], unique=False)

    op.create_table('cost_ledger',
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.Enum('t0_local', 't1_free', 't2_cheap', 't3_strong', name='modeltier_enum', native_enum=False, length=32), nullable=False),
    sa.Column('task_class', sa.Enum('simple', 'normal', 'complex', 'coding', 'vision', 'speech', name='taskclass_enum', native_enum=False, length=32), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('verified_ok', sa.Boolean(), nullable=True),
    sa.Column('is_autonomous', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('input_tokens >= 0 AND output_tokens >= 0', name=op.f('ck_cost_ledger_tokens_non_negative')),
    sa.CheckConstraint('usd >= 0', name=op.f('ck_cost_ledger_usd_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_ledger'))
    )
    with op.batch_alter_table('cost_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_ledger_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_cost_ledger_created_tier', ['created_at', 'tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_ledger_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_ledger_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_cost_ledger_taskclass_tier', ['task_class', 'tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_ledger_tier'), ['tier'], unique=False)

    op.create_table('kill_switch',
    sa.Column('singleton', sa.Boolean(), nullable=False),
    sa.Column('engaged', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('engaged_at', zet.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('engaged_by', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kill_switch')),
    sa.UniqueConstraint('singleton', name=op.f('uq_kill_switch_singleton'))
    )
    with op.batch_alter_table('kill_switch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kill_switch_created_at'), ['created_at'], unique=False)

    op.create_table('owner',
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('permission_level', sa.Enum('read', 'write', 'execute', 'admin', name='permissionlevel_enum', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_owner'))
    )
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owner_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_owner_external_id'), ['external_id'], unique=True)

    op.create_table('quota_ledger',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('window', sa.String(length=16), nullable=False),
    sa.Column('window_start', zet.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('resets_at', zet.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('used >= 0 AND limit_value > 0', name=op.f('ck_quota_ledger_quota_sane')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quota_ledger')),
    sa.UniqueConstraint('provider', 'window', 'window_start', name='unique_quota_window')
    )
    with op.batch_alter_table('quota_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quota_ledger_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_quota_provider_window', ['provider', 'window', 'window_start'], unique=False)

    op.create_table('conversation',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], name=op.f('fk_conversation_owner_id_owner'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation'))
    )
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_owner_id'), ['owner_id'], unique=False)

    op.create_table('message',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', 'tool', name='messagerole_enum', native_enum=False, length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('trust_level', sa.Enum('owner', 'system', 'untrusted', name='trustlevel_enum', native_enum=False, length=32), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('fk_message_conversation_id_conversation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index('ix_message_conversation_created', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_created_at'), ['created_at'], unique=False)

    op.create_table('run',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('parent_run_id', sa.Uuid(), nullable=True),
    sa.Column('trigger', sa.Enum('manual', 'schedule', 'webhook', 'event', 'agent', name='runtrigger_enum', native_enum=False, length=32), nullable=False),
    sa.Column('command_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'planning', 'awaiting_approval', 'executing', 'verifying', 'done', 'failed', 'cancelled', name='runstatus_enum', native_enum=False, length=32), nullable=False),
    sa.Column('intent', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('task_class', sa.Enum('simple', 'normal', 'complex', 'coding', 'vision', 'speech', name='taskclass_enum', native_enum=False, length=32), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('budget_usd', sa.Float(), nullable=False),
    sa.Column('spent_usd', sa.Float(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('verified_ok', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('started_at', zet.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', zet.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('depth >= 0', name=op.f('ck_run_depth_non_negative')),
    sa.CheckConstraint('spent_usd >= 0', name=op.f('ck_run_spent_non_negative')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('fk_run_conversation_id_conversation'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], name=op.f('fk_run_owner_id_owner'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['run.id'], name=op.f('fk_run_parent_run_id_run'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run'))
    )
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_parent_run_id'), ['parent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_status'), ['status'], unique=False)
        batch_op.create_index('ix_run_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_trace_id'), ['trace_id'], unique=False)

    op.create_table('plan',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], name=op.f('fk_plan_run_id_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan')),
    sa.UniqueConstraint('run_id', name='one_plan_per_run')
    )
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_run_id'), ['run_id'], unique=False)

    op.create_table('step',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('agent_name', sa.String(length=64), nullable=True),
    sa.Column('permission_required', sa.Enum('read', 'write', 'execute', 'admin', name='permissionlevel_enum', native_enum=False, length=32), nullable=False),
    sa.Column('trust_context', sa.Enum('owner', 'system', 'untrusted', name='trustlevel_enum', native_enum=False, length=32), nullable=False),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('depends_on', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'awaiting_approval', 'running', 'done', 'failed', 'skipped', name='stepstatus_enum', native_enum=False, length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', zet.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', zet.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('attempt >= 0', name=op.f('ck_step_attempt_non_negative')),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name=op.f('fk_step_plan_id_plan'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_step')),
    sa.UniqueConstraint('plan_id', 'position', name='unique_position_per_plan')
    )
    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index('ix_step_plan_status', ['plan_id', 'status'], unique=False)

    op.create_table('approval',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_permission', sa.Enum('read', 'write', 'execute', 'admin', name='permissionlevel_enum', native_enum=False, length=32), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('preview', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', name='approvalstatus_enum', native_enum=False, length=32), nullable=False),
    sa.Column('expires_at', zet.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('decided_at', zet.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], name=op.f('fk_approval_run_id_run'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], name=op.f('fk_approval_step_id_step'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval'))
    )
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_status'), ['status'], unique=False)
        batch_op.create_index('ix_approval_status_expires', ['status', 'expires_at'], unique=False)

    op.create_table('tool_call',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('permission_level', sa.Enum('read', 'write', 'execute', 'admin', name='permissionlevel_enum', native_enum=False, length=32), nullable=False),
    sa.Column('output_trust_level', sa.Enum('owner', 'system', 'untrusted', name='trustlevel_enum', native_enum=False, length=32), nullable=False),
    sa.Column('input', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('output', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', zet.db.base.UTCDateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], name=op.f('fk_tool_call_run_id_run'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], name=op.f('fk_tool_call_step_id_step'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_call'))
    )
    with op.batch_alter_table('tool_call', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_call_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_tool_call_run_created', ['run_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_call_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_call_step_id'), ['step_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_call_tool_name'), ['tool_name'], unique=False)

    # ### end Alembic commands ###

    # ── audit_log append-only himoyasi (V-33) ──────────────────────
    # ORM darajasida ham bloklangan (zet.db.session), bu — ikkinchi qavat.
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            CREATE OR REPLACE FUNCTION zet_audit_log_immutable()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit_log append-only: % taqiqlangan', TG_OP;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        op.execute(
            """
            CREATE TRIGGER audit_log_no_update_delete
            BEFORE UPDATE OR DELETE ON audit_log
            FOR EACH ROW EXECUTE FUNCTION zet_audit_log_immutable();
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS audit_log_no_update_delete ON audit_log;")
        op.execute("DROP FUNCTION IF EXISTS zet_audit_log_immutable();")

    with op.batch_alter_table('tool_call', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_call_tool_name'))
        batch_op.drop_index(batch_op.f('ix_tool_call_step_id'))
        batch_op.drop_index(batch_op.f('ix_tool_call_run_id'))
        batch_op.drop_index('ix_tool_call_run_created')
        batch_op.drop_index(batch_op.f('ix_tool_call_created_at'))

    op.drop_table('tool_call')
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.drop_index('ix_approval_status_expires')
        batch_op.drop_index(batch_op.f('ix_approval_status'))
        batch_op.drop_index(batch_op.f('ix_approval_run_id'))
        batch_op.drop_index(batch_op.f('ix_approval_created_at'))

    op.drop_table('approval')
    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.drop_index('ix_step_plan_status')
        batch_op.drop_index(batch_op.f('ix_step_plan_id'))
        batch_op.drop_index(batch_op.f('ix_step_created_at'))

    op.drop_table('step')
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_run_id'))
        batch_op.drop_index(batch_op.f('ix_plan_created_at'))

    op.drop_table('plan')
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_trace_id'))
        batch_op.drop_index('ix_run_status_created')
        batch_op.drop_index(batch_op.f('ix_run_status'))
        batch_op.drop_index(batch_op.f('ix_run_parent_run_id'))
        batch_op.drop_index(batch_op.f('ix_run_owner_id'))
        batch_op.drop_index(batch_op.f('ix_run_created_at'))
        batch_op.drop_index(batch_op.f('ix_run_conversation_id'))

    op.drop_table('run')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_created_at'))
        batch_op.drop_index(batch_op.f('ix_message_conversation_id'))
        batch_op.drop_index('ix_message_conversation_created')

    op.drop_table('message')
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_owner_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_created_at'))

    op.drop_table('conversation')
    with op.batch_alter_table('quota_ledger', schema=None) as batch_op:
        batch_op.drop_index('ix_quota_provider_window')
        batch_op.drop_index(batch_op.f('ix_quota_ledger_created_at'))

    op.drop_table('quota_ledger')
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owner_external_id'))
        batch_op.drop_index(batch_op.f('ix_owner_created_at'))

    op.drop_table('owner')
    with op.batch_alter_table('kill_switch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kill_switch_created_at'))

    op.drop_table('kill_switch')
    with op.batch_alter_table('cost_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_ledger_tier'))
        batch_op.drop_index('ix_cost_ledger_taskclass_tier')
        batch_op.drop_index(batch_op.f('ix_cost_ledger_run_id'))
        batch_op.drop_index(batch_op.f('ix_cost_ledger_provider'))
        batch_op.drop_index('ix_cost_ledger_created_tier')
        batch_op.drop_index(batch_op.f('ix_cost_ledger_created_at'))

    op.drop_table('cost_ledger')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_ts_action')
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_log_run_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
